# Generated by Django 2.2.6 on 2019-10-22 14:27

from django.db import migrations, models
import simulator.models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='recording_file',
            field=models.FileField(upload_to=simulator.models.upload_to),
        ),
    ]
