# Generated by Django 2.2.6 on 2019-10-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_auto_20191022_1427'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recording',
            unique_together={('ip_address', 'port')},
        ),
    ]
