# Generated by Django 2.2.6 on 2019-11-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_auto_20191022_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
