# Generated by Django 2.2.6 on 2019-11-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_recording_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='sys_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recording',
            name='comment',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
