# Generated by Django 2.2.6 on 2019-11-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_auto_20191107_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='sys_description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
