# Generated by Django 2.2.6 on 2019-11-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_auto_20191107_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='autodiscover_sys_desc',
            field=models.BooleanField(default=True, verbose_name='Autodiscover sysDescr'),
        ),
    ]
